In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

from estimators import *


In [27]:

num_depths = 2
num_widths = 8
num_actions = num_widths
action_sigma = 0.01

args = dict()
args["action_sigma"] = 1
args["haver_alpha"] = 1.0
args["haver_delta"] = 0.01
args["haver_const"] = 0.1
args["weightedms_num_data"] = 1000

print(f"\n-> max_estimator")
max_action_muhats = np.array([-0.00119, -0.0004,  -0.00232, -0.00229, -4.99928, -4.99792, -4.99743, -5.00378])
max_action_nvisits = np.array([  65., 2262.,  100.,   27.,   15.,   13.,    9.,    9.])
max_mu_est = max_estimator(max_action_muhats)
print(max_mu_est)

print(f"haver_estimator")
haver_action_muhats = np.array([-0.00011, -0.00099,  0.00016, -0.00285, -5.00147, -4.99913, -4.99799, -5.0024 ])
haver_action_nvisits = np.array([  77.,  134., 2213.,   21.,   11.,   18.,   15.,   11.])
haver_action_sigmahats = action_sigma*np.ones(num_actions)
print(haver_action_muhats)
print(haver_action_nvisits)
# print(haver_action_sigmahats)

haver_mu_est, mu_bset = haver_estimator(
    haver_action_muhats, haver_action_sigmahats, 
    num_actions, haver_action_nvisits, args)
                               
print(f"{haver_mu_est:0.05f}")
print(mu_bset)



-> max_estimator
-0.0004
haver_estimator
[-0.0001 -0.001   0.0002 -0.0029 -5.0015 -4.9991 -4.998  -5.0024]
[  77.  134. 2213.   21.   11.   18.   15.   11.]
0.00003
[0, 2]


In [7]:
num_actions = 16
action_probs = np.array([0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.75, 0.02, 0.02,
 0.02, 0.02])
action_probs = action_probs/np.sum(action_probs)
print(action_probs)
cnt_arr = np.zeros(num_actions)
num_samples = 10000
for s in range(num_samples):
    action_s = np.random.choice(num_actions, 1, p=action_probs)[0]
    cnt_arr[action_s] += 1
    
print(cnt_arr)
print(cnt_arr/np.sum(cnt_arr))

[0.019  0.019  0.019  0.019  0.019  0.019  0.019  0.019  0.019  0.019
 0.019  0.7143 0.019  0.019  0.019  0.019 ]
[ 201.  176.  194.  199.  183.  187.  210.  184.  189.  181.  204. 7145.
  184.  184.  182.  197.]
[0.0201 0.0176 0.0194 0.0199 0.0183 0.0187 0.021  0.0184 0.0189 0.0181
 0.0204 0.7145 0.0184 0.0184 0.0182 0.0197]


In [10]:
num_actions = 16
num_data = 100
action_sigmahats = np.zeros(num_actions)
action_muhats = 2*np.ones(num_actions)
samples = np.random.normal(
        action_muhats, action_sigmahats, size=(num_data, num_actions))
print(samples)

[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
